### ISSUE TITLE
First terraform apply fails

### ISSUE THREAD

**Issue by typ-ex** [hashicorp/learn-terraform-resource-targeting#3]
![image](https://user-images.githubusercontent.com/19269683/117894550-2ae3d900-b282-11eb-8bb8-d8b7fb4b08e1.png)

**Comment by typ-ex** [comment]
It'll run if you take "this" out of the values.

**Comment by im2nguyen** [comment]
Just updated the configuration to reflect the updated module outputs, thanks for the catch!
