### ISSUE TITLE
Tutorial correction

### ISSUE THREAD

**Issue by vodelerk** [hashicorp/learn-terraform-resource-targeting#4]
when changing outputs.tf here: 

 output "bucket_name" {
   description = "Randomly generated bucket name."
-  value       = random_pet.bucket_name.id
+  value       = module.s3_bucket.this_s3_bucket_id
 }

generates an error when terraform apply, because this_s3_bucket_id is not defined.

the correct value would be

+ value = module.s3_bucket.s3_bucket_id

**Comment by judithpatudith** [comment]
~Thanks for the report @vodelerk! Could you drop a link to the tutorial that you're seeing this in?~ Never mind, we got it!
