### ISSUE TITLE
This module is currently incompatible with its child module

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/learn-terraform-resource-targeting#8]
This module has been updated to require AWS provider >= v4.0.0 and use the new-style resource types, but it depends on an external module [`terraform-aws-modules/s3-bucket/aws`](https://registry.terraform.io/modules/terraform-aws-modules/s3-bucket/aws) that hasn't yet (as of its v2.14.1) been updated for major version 4 and so at the time of writing produces an unresolvable situation where there is no provider version compatible with all modules:

```
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for
│ provider hashicorp/aws: no available releases
│ match the given constraints ~> 3.69, ~> 4.0.0
╵
```

The external module has added this upper-bounded constraint because it's not yet ready to support AWS provider v4.0.0, so this is a correct error: using provider v4.0.0 with that module would currently produce errors.

I tried rolling back to an earlier commit where this module didn't require AWS provider v4 yet:

```
git checkout 4f83acad0041ed601234570ac71c6e8d72a1ad16
```

Unfortunately, this module is constrained to a particular _minor release_ of the AWS provider and so even then there is no selectable version that is mutually-compatible, but in _this_ case it seems like not a legitimate restriction because the older version of this module is _over-constrained_ -- it would actually be compatible with the latest v3 minor release, as far as I can tell.

I was able to resolve it by temporarily removing this repository's requirement _while still working agaisnt that earlier commit_, and thus letting the child module be the one to decide the version selection:

```diff
diff --git a/main.tf b/main.tf
index 0b5230e..f83ef02 100644
--- a/main.tf
+++ b/main.tf
@@ -2,7 +2,7 @@ terraform {
   required_providers {
     aws = {
       source  = "hashicorp/aws"
-      version = "~> 3.39.0"
+      #version = "~> 3.39.0"
     }
 
     random = {
```

```
$ terraform init -upgrade
Upgrading modules...
Downloading terraform-aws-modules/s3-bucket/aws 2.14.1 for s3_bucket...
- s3_bucket in .terraform/modules/s3_bucket

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 3.69"...
- Finding hashicorp/random versions matching "~> 3.1.0"...
- Using previously-installed hashicorp/aws v3.74.3
- Using previously-installed hashicorp/random v3.1.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

```diff
diff --git a/.terraform.lock.hcl b/.terraform.lock.hcl
index f22f5e1..1636856 100644
--- a/.terraform.lock.hcl
+++ b/.terraform.lock.hcl
@@ -2,21 +2,21 @@
 # Manual edits may be lost in future updates.
 
 provider "registry.terraform.io/hashicorp/aws" {
-  version     = "3.39.0"
-  constraints = ">= 3.36.0, ~> 3.39.0"
+  version     = "3.74.3"
+  constraints = "~> 3.69"
   hashes = [
-    "h1:fjlp3Pd3QsTLghNm7TUh/KnEMM2D3tLb7jsDLs8oWUE=",
-    "zh:2014b397dd93fa55f2f2d1338c19e5b2b77b025a76a6b1fceea0b8696e984b9c",
-    "zh:23d59c68ab50148a0f5c911a801734e9934a1fccd41118a8efb5194135cbd360",
-    "zh:412eab41d4934ca9c47083faa128e4cd585c3bb44ad718e40d67091aebc02f4e",
-    "zh:4b75e0a259b56d97e66b7d69f3f25bd4cc7be2440c0fe35529f46de7d40a49d3",
-    "zh:694a32519dcca5bd8605d06481d16883d55160d97c1f4039deb13c6ca8de8427",
-    "zh:6a0bcef43c2d9a97aeaaac3c5d1d6728dc2464a51a014f118c691c79029d0903",
-    "zh:6d78fc7c663247ca2a80f276008dcdafece4cac75e2639bbce188c08b796040a",
-    "zh:78f846a505d7b64b67feed1527d4d2b40130dadaf8e3112113685e148f49b156",
-    "zh:881bc969432d3ef6ec70f5a762c3415e037904338579b0a360c6818b74d26e59",
-    "zh:96c1ca80c1d693a3eef80489adb45c076ee8e6878e461d6c29b05388d4b95f48",
-    "zh:9be5fa342272586fc6e319e20f21c0c5c801b05dcf7d59e473ad0882c9ecfa70",
+    "h1:h4TYqgRKTuuWfZtxJnEGcs/NxGCaxZ4jr0IwTfgZDRM=",
+    "zh:25401cd4667d0496caf7e92e74ecef7c98cf74465570705cda2207770c27ff6c",
+    "zh:2d154527a9b2585f72fc5eceac635257e3f50f68de8a519e71c795d5166a0a22",
+    "zh:499fa5201804a5a33a90d683147fb2f81da91bfcd8ed20293f88f6f39cedbf97",
+    "zh:730284250fd949a59afb6935b3a68a33709d5a78b686fa98f351ad32c919cfc3",
+    "zh:7461ebd6fb35900d620cfa3f42126d988ea1e604ee3828d1c64d5727f908bd26",
+    "zh:7c85743b31c7459f8e74aaa98471ba82c54517eb908603411808a12982d89b1c",
+    "zh:8ed977b7fb97de624f5414b08cab36fd973a624072e0e9082c0c822e0864c7b9",
+    "zh:94ae7313bb0b425d4007a0b70601a337972c4f0f7a323487acf69215e74b4425",
+    "zh:b5a1589672d709da725a72c46d28bf5b2dea71325f6e0b44a0049f644cd09eba",
+    "zh:c7e8e7ce59e4578416557fc2f138137af3c8365ac3e34f0ff5166323c7d641a1",
+    "zh:ccf2e286b207e749fff76bb4075deddb9e7e237936d8654f34828c54e7035455",
   ]
 }
```

That would not be a good long-term solution because it would make this repository's module potentially break on future major versions of the provider, but it does at least seem to make things work enough to complete [the corresponding tutorial](https://learn.hashicorp.com/tutorials/terraform/resource-targeting).

Until that upstream module has been updated to support AWS provider v4 it may be a good idea to switch this repository back to using the AWS provider v3 schema instead, and to select a specific version of the upstream module that it's known to be compatible with.

```diff
diff --git a/main.tf b/main.tf
index 0b5230e..7112af6 100644
--- a/main.tf
+++ b/main.tf
@@ -2,7 +2,7 @@ terraform {
   required_providers {
     aws = {
       source  = "hashicorp/aws"
-      version = "~> 3.39.0"
+      version = "~> 3.0"
     }
 
     random = {
@@ -23,7 +23,8 @@ resource "random_pet" "bucket_name" {
 }
 
 module "s3_bucket" {
-  source = "terraform-aws-modules/s3-bucket/aws"
+  source  = "terraform-aws-modules/s3-bucket/aws"
+  version = "2.14.1"
 
   bucket = random_pet.bucket_name.id
   acl    = "private"
```

(again, this is a diff relative to commit 4f83acad0041ed601234570ac71c6e8d72a1ad16, which is the last one written to work with v3 of the AWS provider.)

I think this will keep this module working enough for the tutorial to work, while also locking down the dependencies enough to not be broken by future releases of `terraform-aws-modules/s3-bucket/aws` that might support AWS provider v4. Then once that module _is_ ready to support AWS provider v4, we could reintroduce the changes to make this module use v4 too, and change the version pin for `terraform-aws-modules/s3-bucket/aws` to select the newer version.

**Comment by robin-norwood** [comment]
Thanks - reverted to use 3.x until the module is updated!
